services:

  backend:
    image: dnais1210/devops-starter-kit-backend:latest
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    image: dnais1210/devops-starter-kit-frontend:latest
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./app/backend/db:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:

# services:

#   backend:
#     image: dnais1210/devops-starter-kit-backend:latest
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     env_file:
#       - .env
#     networks:
#       - app-network

#   frontend:
#     image: dnais1210/devops-starter-kit-frontend:latest
#     ports:
#       - "5173:80"
#     depends_on:
#       - backend
#     networks:
#       - app-network

#   db:
#     image: postgres:15
#     restart: always
#     env_file:
#       - .env
#     volumes:
#       - db-data:/var/lib/postgresql/data
#       - ./app/backend/db:/docker-entrypoint-initdb.d:ro
#     ports:
#       - "5432:5432"
#     networks:
#       - app-network

#   prometheus:
#     image: prom/prometheus
#     volumes:
#       - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
#     ports:
#       - "9090:9090"
#     depends_on:
#       - backend
#     networks:
#       - app-network

#   grafana:
#     image: grafana/grafana
#     ports:
#       - "3001:3000"
#     depends_on:
#       - prometheus
#     networks:
#       - app-network

# networks:
#   app-network:

# volumes:
#   db-data: